version: 0.2

phases:
  pre_build:
    commands:
      - echo Running prisma migrations...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - set -x
      - set -e
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "Env vars:"
      - echo "NEXT_PUBLIC_GOOGLE_PLACES_API_KEY:$NEXT_PUBLIC_GOOGLE_PLACES_API_KEY"
      - echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
      - echo "NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY:$NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY"
      - echo "NEXT_PUBLIC_API_URL:$NEXT_PUBLIC_API_URL"
      - echo "REPOSITORY_URI:$REPOSITORY_URI"
      - docker build -t "$REPOSITORY_URI:latest" \
        --build-arg NEXT_PUBLIC_GOOGLE_PLACES_API_KEY="$NEXT_PUBLIC_GOOGLE_PLACES_API_KEY" \
        --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" \
        --build-arg NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY="$NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY" \
        --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" . > docker_build.log 2>&1 || cat docker_build.log
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - echo Registering new Task Definition...
      - NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json $TASK_DEFINITION_JSON --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo Updating ecs service with task definition $NEW_TASK_DEFINITION_ARN ...
      - aws ecs update-service --cluster $ECS_CLUSTER_ARN --service $ECS_SERVICE_ID --task-definition $NEW_TASK_DEFINITION_ARN
      - echo Done
