FROM node:18-alpine AS base
WORKDIR /app
COPY . .

ARG NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PRIVATE_API_URL
ARG NEXTAUTH_URL_INTERNAL

RUN echo "NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=${NEXT_PUBLIC_GOOGLE_PLACES_API_KEY}" >> .env.local && \
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}" >> .env.local && \
echo "NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY=${NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY}" >> .env.local && \
echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" && \
echo "NEXT_PRIVATE_API_URL=${NEXT_PRIVATE_API_URL}" && \
echo "NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL}">> .env.local


RUN apk --no-cache add curl && \ 
    npm ci

ENV NODE_ENV=production

RUN npm run build && \
    chmod 755 /app/healthcheck.sh

EXPOSE 3000

CMD ["npm", "start"]